apiVersion: apps/v1
kind: Deployment
metadata:
  name: stem-learning-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stem-learning-platform
  template:
    metadata:
      labels:
        app: stem-learning-platform
    spec:
      containers:
      - name: app
        image: stem-learning-platform:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: stem-learning-platform
spec:
  selector:
    app: stem-learning-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
